# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ViSTA Server V2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Swifter', '~> 1.5'
  pod 'SwiftyJSON', '~> 5.0'
  # Pods for ViSTA Server V2

end
